# Generated by Django 5.1.7 on 2025-03-13 12:07

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_populate_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(default=payments.models.generate_account_number, max_length=16, unique=True),
        ),
    ]
